/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.StudentCourses;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in students_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index STUDENT_COURSES_COURSE_ID = Internal.createIndex(DSL.name("course_id"), StudentCourses.STUDENT_COURSES, new OrderField[] { StudentCourses.STUDENT_COURSES.COURSE_ID }, false);
}
