/*
 * This file is generated by jOOQ.
 */
package jooq;


import java.util.Arrays;
import java.util.List;

import jooq.tables.Courses;
import jooq.tables.StudentCourses;
import jooq.tables.Students;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentsDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>students_db</code>
     */
    public static final StudentsDb STUDENTS_DB = new StudentsDb();

    /**
     * The table <code>students_db.courses</code>.
     */
    public final Courses COURSES = Courses.COURSES;

    /**
     * The table <code>students_db.student_courses</code>.
     */
    public final StudentCourses STUDENT_COURSES = StudentCourses.STUDENT_COURSES;

    /**
     * The table <code>students_db.students</code>.
     */
    public final Students STUDENTS = Students.STUDENTS;

    /**
     * No further instances allowed
     */
    private StudentsDb() {
        super("students_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Courses.COURSES,
            StudentCourses.STUDENT_COURSES,
            Students.STUDENTS
        );
    }
}
