/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Courses;
import jooq.tables.StudentCourses;
import jooq.tables.Students;


/**
 * Convenience access to all tables in students_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>students_db.courses</code>.
     */
    public static final Courses COURSES = Courses.COURSES;

    /**
     * The table <code>students_db.student_courses</code>.
     */
    public static final StudentCourses STUDENT_COURSES = StudentCourses.STUDENT_COURSES;

    /**
     * The table <code>students_db.students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;
}
