/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.util.function.Function;

import jooq.Keys;
import jooq.StudentsDb;
import jooq.tables.records.CoursesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Courses extends TableImpl<CoursesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>students_db.courses</code>
     */
    public static final Courses COURSES = new Courses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoursesRecord> getRecordType() {
        return CoursesRecord.class;
    }

    /**
     * The column <code>students_db.courses.id</code>.
     */
    public final TableField<CoursesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>students_db.courses.courseName</code>.
     */
    public final TableField<CoursesRecord, String> COURSENAME = createField(DSL.name("courseName"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>students_db.courses.courseCredit</code>.
     */
    public final TableField<CoursesRecord, Integer> COURSECREDIT = createField(DSL.name("courseCredit"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>students_db.courses.courseType</code>.
     */
    public final TableField<CoursesRecord, String> COURSETYPE = createField(DSL.name("courseType"), SQLDataType.VARCHAR(50), this, "");

    private Courses(Name alias, Table<CoursesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Courses(Name alias, Table<CoursesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>students_db.courses</code> table reference
     */
    public Courses(String alias) {
        this(DSL.name(alias), COURSES);
    }

    /**
     * Create an aliased <code>students_db.courses</code> table reference
     */
    public Courses(Name alias) {
        this(alias, COURSES);
    }

    /**
     * Create a <code>students_db.courses</code> table reference
     */
    public Courses() {
        this(DSL.name("courses"), null);
    }

    public <O extends Record> Courses(Table<O> child, ForeignKey<O, CoursesRecord> key) {
        super(child, key, COURSES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : StudentsDb.STUDENTS_DB;
    }

    @Override
    public Identity<CoursesRecord, Integer> getIdentity() {
        return (Identity<CoursesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CoursesRecord> getPrimaryKey() {
        return Keys.KEY_COURSES_PRIMARY;
    }

    @Override
    public Courses as(String alias) {
        return new Courses(DSL.name(alias), this);
    }

    @Override
    public Courses as(Name alias) {
        return new Courses(alias, this);
    }

    @Override
    public Courses as(Table<?> alias) {
        return new Courses(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Courses rename(String name) {
        return new Courses(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Courses rename(Name name) {
        return new Courses(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Courses rename(Table<?> name) {
        return new Courses(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super Integer, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Integer, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
