/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.LocalDate;

import jooq.tables.Students;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentsRecord extends UpdatableRecordImpl<StudentsRecord> implements Record5<Integer, String, String, String, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>students_db.students.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>students_db.students.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>students_db.students.idNumber</code>.
     */
    public void setIdnumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>students_db.students.idNumber</code>.
     */
    public String getIdnumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>students_db.students.firstName</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>students_db.students.firstName</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>students_db.students.lastName</code>.
     */
    public void setLastname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>students_db.students.lastName</code>.
     */
    public String getLastname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>students_db.students.registrationDate</code>.
     */
    public void setRegistrationdate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>students_db.students.registrationDate</code>.
     */
    public LocalDate getRegistrationdate() {
        return (LocalDate) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, LocalDate> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, LocalDate> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Students.STUDENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Students.STUDENTS.IDNUMBER;
    }

    @Override
    public Field<String> field3() {
        return Students.STUDENTS.FIRSTNAME;
    }

    @Override
    public Field<String> field4() {
        return Students.STUDENTS.LASTNAME;
    }

    @Override
    public Field<LocalDate> field5() {
        return Students.STUDENTS.REGISTRATIONDATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getIdnumber();
    }

    @Override
    public String component3() {
        return getFirstname();
    }

    @Override
    public String component4() {
        return getLastname();
    }

    @Override
    public LocalDate component5() {
        return getRegistrationdate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getIdnumber();
    }

    @Override
    public String value3() {
        return getFirstname();
    }

    @Override
    public String value4() {
        return getLastname();
    }

    @Override
    public LocalDate value5() {
        return getRegistrationdate();
    }

    @Override
    public StudentsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public StudentsRecord value2(String value) {
        setIdnumber(value);
        return this;
    }

    @Override
    public StudentsRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public StudentsRecord value4(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public StudentsRecord value5(LocalDate value) {
        setRegistrationdate(value);
        return this;
    }

    @Override
    public StudentsRecord values(Integer value1, String value2, String value3, String value4, LocalDate value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentsRecord
     */
    public StudentsRecord() {
        super(Students.STUDENTS);
    }

    /**
     * Create a detached, initialised StudentsRecord
     */
    public StudentsRecord(Integer id, String idnumber, String firstname, String lastname, LocalDate registrationdate) {
        super(Students.STUDENTS);

        setId(id);
        setIdnumber(idnumber);
        setFirstname(firstname);
        setLastname(lastname);
        setRegistrationdate(registrationdate);
        resetChangedOnNotNull();
    }
}
